# Generated by Django 4.2.5 on 2023-12-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('ISBN', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Fiction', 'fiction'), ('mythology', 'mythology'), ('drama', 'drama'), ('others', 'others')], max_length=100)),
                ('publish_year', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
