# Generated by Django 4.2.5 on 2023-12-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0002_bookshelf_reviews_alter_bookshelf_publish_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='reviews',
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('reviews', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapi.bookshelf')),
            ],
        ),
    ]
