# Generated by Django 4.2.5 on 2023-12-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0003_remove_bookshelf_reviews_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='ISBN',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
